# syntax=docker/dockerfile:1

ARG ALPINE_VERSION=3.21

FROM alpine:$ALPINE_VERSION AS base

ARG TARGETOS
ARG TARGETARCH

ARG SUPERCRONIC_VERSION=0.2.33
ARG PG_BACK_VERSION=2.5.0

RUN apk add --no-cache zip curl \
    # Install supercronic
    && curl -fsSLO "https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-${TARGETOS}-${TARGETARCH}" \
        && mv "supercronic-${TARGETOS}-${TARGETARCH}" "/tmp/supercronic"

FROM --platform=$BUILDPLATFORM alpine:$ALPINE_VERSION

RUN apk add --no-cache \
    bash=5.2.37-r0 \
    gomplate=4.2.0-r5 \
    postgresql17-client=17.5-r0 # pg_back need pg_dump, then PostgreSQL version 17.5 is installed

COPY --from=base --chmod=0755 /tmp/supercronic /usr/local/bin/supercronic

ADD src/github.com/orgrim/pg_back/pg_back /usr/local/bin/pg_back

COPY ./pg_back.conf.tmpl /pg_back.conf.tmpl
COPY --chmod=0755 ./entrypoint.sh /entrypoint.sh

ENV POSTGRES_HOST="postres"
ENV POSTGRES_PORT="5432"
ENV POSTGRES_USER="postgres"
ENV POSTGRES_DBNAME="postgres"
ENV POSTGRES_PASSWORD="password"

# Daily
ENV BACKUP_CRON="0 3 * * *"
ENV DISABLE_CRON="false"

ENTRYPOINT [ "/entrypoint.sh" ]
