name: Build Docker Image for testing
on: [pull_request]

jobs:
  docker_build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for docker Buildx
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Generate tag
        id: tag
        run: |
          DATETIME=$(date '+%Y%m%d%H%M%S')
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "docker_tag=${DATETIME}-${SHORT_SHA}-pg_backv2.6.0" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: stephaneklein/pg_back-docker-sidecar:${{ steps.tag.outputs.docker_tag }}
