name: Build and Push Docker Image
on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for docker Buildx
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: stephaneklein
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: tag
        run: |
          DATETIME=$(date '+%Y%m%d%H%M%S')
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "docker_tag=${DATETIME}-${SHORT_SHA}-sklein-fork" >> $GITHUB_OUTPUT

      # `sklein-fork` contains the code from the following branch https://github.com/stephane-klein/pg_back/commits/sklein-main/
      # when this Pull Request will be merged https://github.com/orgrim/pg_back/pull/147
      # `sklein-fork` will be replaced by `pg_back2.5.0`

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            stephaneklein/pg_back-docker-sidecar:latest
            stephaneklein/pg_back-docker-sidecar:${{ steps.tag.outputs.docker_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.docker_tag }}
          name: "${{ steps.tag.outputs.docker_tag }}"
          body: |
            Here's how to pull the Docker image for this release:

            ```
            $ docker pull docker.io/stephaneklein/pg_back-docker-sidecar:${{ steps.tag.outputs.docker_tag }}
            ```
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
